In [9]:
using HDF5
using NCDatasets

In [34]:
output_ds = h5open("./ALEX_VERIFICATION/mined_out.h5")
ALEX_output_ds = h5open("./ALEX_VERIFICATION/Isaac_test.h5")
verification = read(output_ds["Y"])

31464-element Vector{Int64}:
 0
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [28]:
read(ALEX_output_ds["Y"])

31464-element Vector{Int64}:
 0
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [12]:
cfrad = Dataset("ALEX_VERIFICATION/cfrad.20050922_181903.467_to_20050922_181906.771_TA-ELDR_AIR.nc")

Dataset: ALEX_VERIFICATION/cfrad.20050922_181903.467_to_20050922_181906.771_TA-ELDR_AIR.nc
Group: /

Dimensions
   time = 268
   range = 400
   sweep = 1
   string_length_8 = 8
   string_length_32 = 32
   status_xml_length = 1
   r_calib = 1
   frequency = 4

Variables
  volume_number  
    Attributes:
     long_name            = data_volume_index_number
     units                = 
     _FillValue           = -9999

  platform_type   (32)
    Datatype:    Char (Char)
    Dimensions:  string_length_32
    Attributes:
     long_name            = platform_type
     options              = fixed, vehicle, ship, aircraft_fore, aircraft_aft, aircraft_tail, aircraft_belly, aircraft_roof, aircraft_nose, satellite_orbit, satellite_geostat

  primary_axis   (32)
    Datatype:    Char (Char)
    Dimensions:  string_length_32
    Attributes:
     long_name            = primary_axis_of_rotation
     options              = axis_z, axis_y, axis_x, axis_z_prime, axis_y_prime, axis_x_prime

  status_xm

In [25]:
Y = reshape([ismissing(x) ? 0 : 1 for x in cfrad["VG"] .- cfrad["VV"]][:], (:, 1))


107200×1 Matrix{Int64}:
 0
 0
 0
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [26]:
Y[indexer]

1528-element Vector{Int64}:
 0
 0
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [21]:
X = Matrix{Float64}(undef,cfrad.dim["time"] * cfrad.dim["range"], 1)
X[1,1] = -35


-35

In [24]:
Y

23648×1 Matrix{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [22]:
indexer = X[:, 1] .> 0

107200-element BitVector:
 0
 1
 1
 1
 1
 1
 1
 1
 0
 0
 0
 1
 1
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [6]:
Set([1,2,2])

Set{Int64} with 2 elements:
  2
  1